spring:
  datasource:
    username: test
    password: 1234
    url: jdbc:mariadb://localhost:3306/jecar
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080



#spring:
#  datasource:
#    username: minsung
#    password: dhalstjd1
#    url: jdbc:mysql://localhost:3306/minsung
#  jpa:
#    hibernate:
#      ddl-auto: update
#server:
#  port: 8080